---
# tasks file for fluentd-packages

- name: Stop the fluentd service.
  service: name=td-agent state=stopped
  ignore_errors: true

- include: redhat.yml
  when: ansible_os_family == 'RedHat'

- include: debian.yml
  when: ansible_os_family == 'Debian'
